**Importing Libraries**

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

**Reading the data**

In [16]:
data_df = pd.read_csv('/content/Lagos_GDP_Population_Dataset.csv')
data_df.head()

row_id                                        source  latitude  longitude  \
0  185053  Federal Ministry of Water Resources, Nigeria  6.601190   3.394098   
1  185368  Federal Ministry of Water Resources, Nigeria  6.674977   3.712242   
2  185381  Federal Ministry of Water Resources, Nigeria  6.413153   4.087083   
3  185740  Federal Ministry of Water Resources, Nigeria  6.583227   3.981810   
4  185627  Federal Ministry of Water Resources, Nigeria  6.630905   3.986448   

        report_date status_id                    water_source  \
0  16-05-2015 00:00       Yes     Improved Protected dug well   
1  29-05-2015 00:00       Yes     Improved Protected dug well   
2  08-06-2015 00:00        No  Improved Tube well or borehole   
3  27-05-2015 00:00       Yes  Improved Tube well or borehole   
4  31-05-2015 00:00       Yes  Improved Tube well or borehole   

       water_source_clean water_tech_clean water_tech  ...  \
0  Protected Shallow Well  Mechanized Pump  Motorised  ...   
1        Protected Spring              NaN    Gravity  ...   
2                Borehole  Mechanized Pump  Motorised  ...   
3                Borehole  Mechanized Pump  Motorised  ...   
4                Borehole  Mechanized Pump  Motorised  ...   

            water_source_original             management_clean  \
0     improved protected dug well  Direct Government Operation   
1                         gravity            School Management   
2  improved tube well or borehole                          NaN   
3  improved tube well or borehole                        Other   
4  improved tube well or borehole         Community Management   

                 management_original water_source_category  \
0        direct government operation                  Well   
1  institutional management - school                Spring   
2                                NaN                  Well   
3                              other                  Well   
4               community management                  Well   

  water_tech_category count population  \
0     Mechanized Pump     1     665421   
1                 NaN     1     181715   
2     Mechanized Pump     1     117542   
3     Mechanized Pump     1     181715   
4     Mechanized Pump     1     181715   

  classification_as_urban/semi-urban/rural income_classification  \
0                               Semi-urban         Middle-income   
1                                    Rural            Low-income   
2                                    Urban           High-income   
3                                    Rural            Low-income   
4                                    Rural            Low-income   

  water_demand(lpcd)  
0             70-120  
1              50-70  
2            120-150  
3              50-70  
4              50-70  

[5 rows x 29 columns]

In [17]:
data_df.tail()

row_id                                        source  latitude  \
1501  186120  Federal Ministry of Water Resources, Nigeria  6.490502   
1502  185732  Federal Ministry of Water Resources, Nigeria  6.489920   
1503  185478  Federal Ministry of Water Resources, Nigeria  6.550210   
1504  185182  Federal Ministry of Water Resources, Nigeria  6.444647   
1505  185914  Federal Ministry of Water Resources, Nigeria  6.575418   

      longitude       report_date status_id                    water_source  \
1501   2.958010  10-06-2015 00:00        No  Improved Tube well or borehole   
1502   3.335282  22-05-2015 00:00       Yes  Improved Tube well or borehole   
1503   3.331012  09-05-2015 00:00       Yes  Improved Tube well or borehole   
1504   2.900488  08-06-2015 00:00       Yes  Improved Tube well or borehole   
1505   3.280898  26-05-2015 00:00       Yes  Improved Tube well or borehole   

     water_source_clean water_tech_clean water_tech  ...  \
1501           Borehole  Mechanized Pump  Motorised  ...   
1502           Borehole  Mechanized Pump  Motorised  ...   
1503           Borehole  Mechanized Pump  Motorised  ...   
1504           Borehole  Mechanized Pump  Motorised  ...   
1505           Borehole  Mechanized Pump  Motorised  ...   

               water_source_original      management_clean  \
1501  improved tube well or borehole  Community Management   
1502  improved tube well or borehole                 Other   
1503  improved tube well or borehole  Community Management   
1504  improved tube well or borehole  Community Management   
1505  improved tube well or borehole                 Other   

       management_original water_source_category water_tech_category count  \
1501  community management                  Well     Mechanized Pump     1   
1502                 other                  Well     Mechanized Pump     1   
1503  community management                  Well     Mechanized Pump     1   
1504  community management                  Well     Mechanized Pump     1   
1505                 other                  Well     Mechanized Pump     1   

     population classification_as_urban/semi-urban/rural  \
1501     241437                                    Rural   
1502     504409                               Semi-urban   
1503    1621789                               Semi-urban   
1504     241437                                    Rural   
1505   11456783                               Semi-urban   

     income_classification water_demand(lpcd)  
1501            Low-income              50-70  
1502         Middle-income             70-120  
1503         Middle-income             70-120  
1504            Low-income              50-70  
1505         Middle-income             70-120  

[5 rows x 29 columns]

**Columns in the dataset**

In [18]:
data_df.columns

Index(['row_id', 'source', 'latitude', 'longitude', 'report_date', 'status_id',
       'water_source', 'water_source_clean', 'water_tech_clean', 'water_tech',
       'facility_type', 'adm2', 'management', 'pay', 'status',
       'subjective_quality', 'address', 'photo_lnk', 'water_tech_original',
       'water_source_original', 'management_clean', 'management_original',
       'water_source_category', 'water_tech_category', 'count', 'population',
       'classification_as_urban/semi-urban/rural', 'income_classification',
       'water_demand(lpcd)'],
      dtype='object')

**Getting overall info from the data**

In [19]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1506 entries, 0 to 1505
Data columns (total 29 columns):
 #   Column                                    Non-Null Count  Dtype  
---  ------                                    --------------  -----  
 0   row_id                                    1506 non-null   int64  
 1   source                                    1506 non-null   object 
 2   latitude                                  1506 non-null   float64
 3   longitude                                 1506 non-null   float64
 4   report_date                               1506 non-null   object 
 5   status_id                                 1506 non-null   object 
 6   water_source                              1506 non-null   object 
 7   water_source_clean                        1506 non-null   object 
 8   water_tech_clean                          1454 non-null   object 
 9   water_tech                                1506 non-null   object 
 10  facility_type                       

**Overall info to check rows and columns**

In [20]:
for i in data_df.columns:
    print("column name :",i)
    print("No. of column :",len(data_df[i].unique()))
    print(data_df[i].unique())

column name : row_id
No. of column : 1506
[185053 185368 185381 ... 185478 185182 185914]
column name : source
No. of column : 1
['Federal Ministry of Water Resources, Nigeria']
column name : latitude
No. of column : 1473
[6.60119   6.6749767 6.4131533 ... 6.55021   6.4446467 6.5754183]
column name : longitude
No. of column : 1477
[3.3940983 3.7122417 4.0870833 ... 3.3310117 2.9004883 3.2808983]
column name : report_date
No. of column : 37
['16-05-2015 00:00' '29-05-2015 00:00' '08-06-2015 00:00'
 '27-05-2015 00:00' '31-05-2015 00:00' '26-05-2015 00:00'
 '09-05-2015 00:00' '15-05-2015 00:00' '13-05-2015 00:00'
 '19-05-2015 00:00' '11-05-2015 00:00' '23-05-2015 00:00'
 '07-05-2015 00:00' '28-05-2015 00:00' '01-06-2015 00:00'
 '10-05-2015 00:00' '04-06-2015 00:00' '17-05-2015 00:00'
 '18-05-2015 00:00' '03-06-2015 00:00' '22-05-2015 00:00'
 '20-05-2015 00:00' '12-05-2015 00:00' '25-05-2015 00:00'
 '14-05-2015 00:00' '06-06-2015 00:00' '30-05-2015 00:00'
 '10-06-2015 00:00' '21-05-2015 00

**Correction for repetitive values in the column water_tech**

In [21]:
corrections={'tap':'Tap','solar':'Solar','hand pump':'Hand pump','Tap':'Tap','Solar':'Solar','Hand pump':'Hand pump','Motorised':'Motorised','Gravity':'Gravity','Manual':'Manual','Elevated Tank ':'Elevated Tank','pipe borne water':'pipe borne water','Public Tap':'Public Tap','No water':'No water','From water supply':'From water supply','ground storage and elevated tank':'ground storage and elevated tank','Landed and Gravity  Tank':'Landed and Gravity Tank','Gravity motorise':'Gravity motorise','Tap pipe':'Tap pipe','Elevated tank and UPVC Town Distribution':'Elevated tank and UPVC Town Distribution'}
data_df.water_tech.replace(corrections)
data_df.water_tech = data_df.water_tech.map(corrections)

In [22]:
for i in data_df.columns:
    print("column name :",i)
    print("No. of column :",len(data_df[i].unique()))
    print(data_df[i].unique())

column name : row_id
No. of column : 1506
[185053 185368 185381 ... 185478 185182 185914]
column name : source
No. of column : 1
['Federal Ministry of Water Resources, Nigeria']
column name : latitude
No. of column : 1473
[6.60119   6.6749767 6.4131533 ... 6.55021   6.4446467 6.5754183]
column name : longitude
No. of column : 1477
[3.3940983 3.7122417 4.0870833 ... 3.3310117 2.9004883 3.2808983]
column name : report_date
No. of column : 37
['16-05-2015 00:00' '29-05-2015 00:00' '08-06-2015 00:00'
 '27-05-2015 00:00' '31-05-2015 00:00' '26-05-2015 00:00'
 '09-05-2015 00:00' '15-05-2015 00:00' '13-05-2015 00:00'
 '19-05-2015 00:00' '11-05-2015 00:00' '23-05-2015 00:00'
 '07-05-2015 00:00' '28-05-2015 00:00' '01-06-2015 00:00'
 '10-05-2015 00:00' '04-06-2015 00:00' '17-05-2015 00:00'
 '18-05-2015 00:00' '03-06-2015 00:00' '22-05-2015 00:00'
 '20-05-2015 00:00' '12-05-2015 00:00' '25-05-2015 00:00'
 '14-05-2015 00:00' '06-06-2015 00:00' '30-05-2015 00:00'
 '10-06-2015 00:00' '21-05-2015 00

In [23]:
px.set_mapbox_access_token("pk.eyJ1Ijoic291cm95MDIyMSIsImEiOiJjbDR4djh6M24wN2k5M2NvNmtubXJybXZpIn0.OOttJSAJLrkuIqWdYt1hPQ")

**GIS Visualization**

In [25]:
fig = px.scatter_mapbox(data_df, lat="latitude", lon="longitude", color="adm2",hover_data=["population","income_classification","water_demand(lpcd)","classification_as_urban/semi-urban/rural","status","report_date","water_tech","pay","subjective_quality","water_source_category","address"],
                            color_continuous_scale=px.colors.sequential.Rainbow, zoom=10,mapbox_style="open-street-map",size="latitude",
                        title="Information about waterworks in Lagos Nigeria")

fig